############################# 访问路径、端口tomcat start #############################
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
############################# 访问路径、端口tomcat end ###############################

############################# 日志、监控配置 start ########################################
logging:
  level:
    com.feng: debug
    org.springframework: info

# 监控/actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics
  endpoint:
    health:
      show-details: always
############################# 日志配置 end ###########################################

################################ spring config start ###############################
spring:
  application:
    name: SpringBlog
  profiles:
    active: dev
  thymeleaf:
    # 开启模板缓存（默认值： true ）
    cache: true
    # 检查模板是否存在，然后再呈现
    check-template: true
    # 检查模板位置是否正确（默认值 :true ）
    check-template-location: true
    # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    enabled: true
    # 模板编码
    encoding: utf-8
    # 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
    mode: HTML
    # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    prefix: classpath:/templates/
    # 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
    suffix: .html
    servlet:
      #Content-Type 的值（默认值： text/html ）
      content-type: text/html
################################ spring config end #################################

############################### Redis 公共配置 start ###############################
---
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    #超时连接
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接,设 0 为没有限制
        min-idle: 0
        # 连接池中的最大空闲连接,设 0 为没有限制
        max-idle: 8
        # 连接池的最大数据库连接数,设 0 为没有限制
        max-active: 8
        # 连接池最大阻塞等待时间,如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: 10s
      shutdown-timeout: 3s
############################### Redis 公共配置 end ##################################

############################### 异步线程配置 start ##################################
async:
  executor:
    thread:
      # 配置核心线程数
      core_pool_size: 5
      # 配置最大线程数
      max_pool_size: 5
      # 配置队列大小
      queue_capacity: 1000
      # 配置线程池中的线程的名称前缀
      name:
        prefix: async-service-
